/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package jdbc_emp;

import java.util.ArrayList;

import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author USER
 */
public class EmpManagerGui extends javax.swing.JFrame {

	private DeptDAO deptDao;
			EmpDAO empDao;
	private DefaultTableModel dmodel, emodel; // 부서 테이블 모델, 사원 테이블 모델 선언
	String []colHeader1 = { "부서번호", "부서명", "부서위치" };
	String []colHeader2 = { "사번", "사원명", "부서번호", "부서명", "담당업무", "입사일" };
	MyMouseEventHandler handler;
	
	DefaultComboBoxModel<String> comboModel;
	String dnames[]; // "부서번호: 부서명" 형태의 정보를 저장할 배열
			
    public EmpManagerGui() {
    	super("::EmpManagerGui v1.0::");
        initComponents();
        deptDao=new DeptDAO();
        empDao=new EmpDAO();
        tabPane.setSelectedIndex(0); // 첫번째 탭을 선택하도록
        tdeptno.setEditable(false); // 부서번호 편집 못하도록
        tempno.setEditable(false); // 사번 편집 못하도록
        thiredate.setEditable(false); // 입사일 편집 못하도록
        
        // 부서정보 가져오기
        ArrayList<DeptVO> arr = deptDao.allDept();
        dnames = new String[arr.size()];
        if(arr!=null && arr.size()>0) {
        	for(int i=0; i<arr.size(); i++) {
        		DeptVO dvo = arr.get(i);
        		dnames[i] = dvo.getDeptno()+": "+dvo.getDname();
        	}
        }
        comboModel = new DefaultComboBoxModel(dnames);
        this.cdname.setModel(comboModel);
        
        // 리스너 부착
        handler = new MyMouseEventHandler(this);
        tableDept.addMouseListener(handler);
        tableEmp.addMouseListener(handler);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tabPane = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tdname = new javax.swing.JTextField();
        tloc = new javax.swing.JTextField();
        tdeptno = new javax.swing.JTextField();
        btDlist = new javax.swing.JButton();
        btDadd = new javax.swing.JButton();
        btDdel = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableDept = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        tjob = new javax.swing.JTextField();
        cdname = new javax.swing.JComboBox();
        tcomm = new javax.swing.JTextField();
        tempno = new javax.swing.JTextField();
        tename = new javax.swing.JTextField();
        thiredate = new javax.swing.JTextField();
        tsal = new javax.swing.JTextField();
        btEadd = new javax.swing.JButton();
        btElist = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableEmp = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        btEedit = new javax.swing.JButton();
        btFind = new javax.swing.JButton();
        btEdel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("휴먼엑스포", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 0, 51));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("::: TIS 인사관리 시스템 v1.0 :::");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logo.png"))); // NOI18N
        jLabel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jPanel1.setBackground(new java.awt.Color(0, 51, 51));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 153), 3));

        jLabel3.setText("부서 번호");

        jLabel4.setText("부  서  명");

        jLabel5.setText("부서 위치");

        tdeptno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tdeptnoActionPerformed(evt);
            }
        });

        btDlist.setText("목  록");
        btDlist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDlistActionPerformed(evt);
            }
        });

        btDadd.setText("등   록");
        btDadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDaddActionPerformed(evt);
            }
        });

        btDdel.setText("삭  제");
        btDdel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDdelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tdname, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tdeptno, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tloc, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(btDadd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btDlist)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btDdel)
                        .addGap(0, 119, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tdeptno, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tdname, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tloc, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btDlist, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btDdel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btDadd, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26))
        );

        tableDept.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null}
            },
            new String [] {
                "부서 번호", "부  서  명", "부서 위치"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tableDept);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        tabPane.addTab("부서관리", jPanel1);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 0, 102), 3));

        jLabel6.setText(" 사       번");

        jLabel7.setText("사원  이름");

        jLabel8.setText("부  서   명");

        jLabel9.setText("담당  업무");

        jLabel10.setText("입  사  일");

        jLabel11.setText("월  급  여");

        jLabel12.setText("보  너  스");

        cdname.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1" }));

        tename.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tenameActionPerformed(evt);
            }
        });

        btEadd.setBackground(new java.awt.Color(153, 255, 153));
        btEadd.setText("사원 정보 등록");
        btEadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEaddActionPerformed(evt);
            }
        });

        btElist.setBackground(new java.awt.Color(255, 153, 153));
        btElist.setText("모든 사원 목록");
        btElist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btElistActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel12)
                    .addComponent(jLabel11)
                    .addComponent(jLabel10)
                    .addComponent(jLabel9)
                    .addComponent(jLabel8)
                    .addComponent(jLabel7)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cdname, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tjob, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tcomm, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tempno, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tename, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(thiredate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tsal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addComponent(btEadd)
                .addGap(18, 18, 18)
                .addComponent(btElist)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btEadd, btElist});

        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(tempno, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(tename, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addComponent(jLabel8))
                    .addComponent(cdname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(tjob, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel10)
                    .addComponent(thiredate, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(tsal, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(tcomm, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btEadd, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btElist))
                .addGap(34, 34, 34))
        );

        jPanel4Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btEadd, btElist});

        tableEmp.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tableEmp.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "사번", "사원명", "부서번호", "부서명", "담당업무", "입사일"
            }
        ));
        jScrollPane2.setViewportView(tableEmp);

        btEedit.setText("사원 정보 수정");
        btEedit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEeditActionPerformed(evt);
            }
        });

        btFind.setText("사원 정보 검색");
        btFind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btFindActionPerformed(evt);
            }
        });

        btEdel.setText("사원 정보 삭제");
        btEdel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEdelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(btEedit)
                .addGap(18, 18, 18)
                .addComponent(btFind)
                .addGap(18, 18, 18)
                .addComponent(btEdel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btEdel, btEedit, btFind});

        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btFind)
                    .addComponent(btEdel)
                    .addComponent(btEedit, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jPanel5Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btEdel, btEedit, btFind});

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 470, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 10, Short.MAX_VALUE))
        );

        tabPane.addTab("인사관리", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 434, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(tabPane)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jLabel2)))
                .addGap(18, 18, 18)
                .addComponent(tabPane, javax.swing.GroupLayout.PREFERRED_SIZE, 488, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tdeptnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tdeptnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tdeptnoActionPerformed

    private void btElistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btElistActionPerformed
        showAllEmpInfo();
    }//GEN-LAST:event_btElistActionPerformed

    private void showAllEmpInfo() {
		ArrayList<EmpVO> empList = empDao.selectEmpAll();
		showEmpTable(empList);
	} //------------------------

	private void showEmpTable(ArrayList<EmpVO> empList) {
		Object [][]data = new Object[empList.size()][6];
		for(int i=0; i<empList.size(); i++) {
			EmpVO emp = empList.get(i); //하나의 행(레코드)
			data[i][0] = emp.getEmpno();
			data[i][1] = emp.getEname();
			data[i][2] = emp.getDeptno();
			data[i][3] = emp.getDname();
			data[i][4] = emp.getJob();
			data[i][5] = emp.getHiredate();
		} // for------------
		this.emodel = new DefaultTableModel(data, colHeader2);
		tableEmp.setModel(emodel);
	} //------------------------

	private void btEaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEaddActionPerformed
        // 1. 이름, 부서명, 업무, 급여, 보너스 값 받아오기
    	String ename = this.tename.getText();
        String dinfo = this.cdname.getSelectedItem().toString();
        // setTitle(dinfo);
        
        // ':' 을 기준으로 문자열을 쪼개어 배열로 반환한다.
        String token[] = dinfo.split("\\:");
        // token[0] => 부서번호, token[1] => 부서명
        //setTitle(token[0]);
        String deptno = (token[0]!=null)? token[0].trim(): "";
        String dname = (token[1]!=null)? token[1].trim(): "";
        
        String job = this.tjob.getText();
        String sal = this.tsal.getText();
        String comm = this.tcomm.getText();
        
        // 2. 유효성 체크(not null 컬럼은 필히 체크)
        if(ename==null||dinfo==null||ename.trim().isEmpty()||dinfo.trim().isEmpty()) {
        	showMsg("사원명과 부서선택은 필수 입력사항입니다.");
        	tename.requestFocus();
        	return;
        }
        
        int sal2 = Integer.parseInt(sal);
        int deptno2 = Integer.parseInt(deptno);
        int comm2 = (deptno2==30)? Integer.parseInt(comm): 0;
        
        // 3. 받아온 값으로 EmpVO 객체 생성
        EmpVO emp = new EmpVO(0, ename, job, 7788, null, sal2, comm2, deptno2, dname);
                
        // 4. empDao의 insertEmp() 호출
        boolean result = empDao.insertEmp(emp);
        
        // 5. 그 실행 결과 메시지 처리
        String message = (result)? "사원 정보 등록 성공": "등록 실패";
        showMsg(message);
        showAllEmpInfo();
        
    }//-------------------------

    private void tenameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tenameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tenameActionPerformed

    public void showMsg(String message) {
    	JOptionPane.showMessageDialog(this, message);
    }
    
    private void btDaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDaddActionPerformed
        //1) 사용자가 입력한 부서명, 근무지 얻어오기
    	String dname=tdname.getText();
    	String loc=tloc.getText();
    	
    	//2) 널체크, 빈문자열 체크 -유효성 체크
    	if(dname==null||loc==null||dname.trim().isEmpty()||loc.trim().isEmpty()) {
    		//dname.trim().isEmpty() -> trim 앞뒤 공백제거, isEmpty -> 비어있나
    		showMsg("부서명과 부서위치를 입력하세요");
    		tdname.requestFocus();
    		return;
    	}
    	
    	//3) DeptVO객체 생성해서 얻어온 값들 setting
    	DeptVO dvo = new DeptVO();
    	dvo.setDname(dname);
    	dvo.setLoc(loc);
    	
    	//4) deptDao의 insertDept()메소드 호출하기
    	//   그 결과값에 따른 메시지 처리 (등록 성공 or 등록 실패)
    	boolean result = deptDao.insertDept(dvo);
    	String message = (result)? "등록 성공":"등록 실패";
    	showMsg(message);
    	if(result) { // 잘 등록됐다면...부서 테이블 목록 보여주기
    		showAllDeptInfo(); // 정보 모듈화하여 재사용성 높게    		
    	}
    	
    }//GEN-LAST:event_btDaddActionPerformed
    
    public void showAllDeptInfo() { // 정보 모듈화하여 재사용성 높게
    	ArrayList<DeptVO> dlist=deptDao.allDept();
    	showDeptTable(dlist);
    }
    public void showDeptTable(ArrayList<DeptVO> dlist) {
    	Object [][] data = new Object[dlist.size()][3]; // 2차원 배열 생성
        
        // ArrayList에 저장된 데이터를 2차원 배열에 옮기자.
        for(int i=0; i<data.length; i++) {
        	DeptVO dept = dlist.get(i); //하나의 레코드(행의 정보)
        	data[i][0] = dept.getDeptno(); // 부서번호
        	data[i][1] = dept.getDname(); // 부서명
        	data[i][2] = dept.getLoc(); // 부서위치
        }
        // 부서 테이블 모델
        dmodel = new DefaultTableModel(data, colHeader1);
        
        // 뷰와 모델을 연결
        tableDept.setModel(dmodel);
    } // showDeptTable-----------------

    private void btDlistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDlistActionPerformed
        showAllDeptInfo();
        
    }//GEN-LAST:event_btDlistActionPerformed

    private void btDdelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDdelActionPerformed
        String deptno = tdeptno.getText();
        if(deptno==null||deptno.trim().isEmpty()) {
        	showMsg("삭제할 부서를 테이블에서 선택하세요.");
        	return;
        }
        // 삭제 의사를 확인
        int yn = JOptionPane.showConfirmDialog(this, deptno+"번 부서를 정말 삭제할까요?",
        		"삭제확인", JOptionPane.YES_NO_OPTION);
        if(yn==JOptionPane.NO_OPTION) return;
        // deptDao의 삭제 처리 메소드 호출
        boolean result = deptDao.deleteDept(deptno);
        // 그 실행 결과 메시지 처리(삭제 성공 or 실패)
        String message = (result)? "삭제 성공":"삭제 실패-해당 부서에 소속된 직원이 존재합니다.";
        showMsg(message);
        // 모든 부서정보 가져오기
        this.showAllDeptInfo();
    }//-----------------------------

    private void btEeditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEeditActionPerformed
        // 1. 수정할 값들 얻어오기
    	String empno = tempno.getText();
    	String ename = tename.getText();
    	String dinfo = cdname.getSelectedItem().toString();
    	String []token = dinfo.split("\\:");
    	String deptnoStr = token[0].trim();
    	String dname = token[1].trim();
    	
    	String job = tjob.getText();
    	String comm = tcomm.getText();
    	String sal = tsal.getText();
    	// 2. 유효성 체크
    	if(empno==null||ename==null||
    			empno.trim().isEmpty()||ename.trim().isEmpty()) {
    		showMsg("수정할 사원을 사원정보 테이블에서 선택하세요");
    		return;
    	}
    	// 3. 해당 값들을 EmpVO 객체에 담아주기
    	int empno2 = Integer.parseInt(empno.trim());
    	int deptno2 = Integer.parseInt(deptnoStr);
    	int sal2 = Integer.parseInt(sal.trim());
    	int comm2 = Integer.parseInt(comm.trim());
    	EmpVO emp = new EmpVO(empno2, ename, job, 7788, null, sal2, comm2, deptno2, null);
    	// 4. empDao의 updateEmp() 호출하기
    	boolean result = empDao.updateEmp(emp);
    	String message = (result)? "수정 성공": "수정 실패";
    	// 5. 그 결과 메시지 처리
    	showMsg(message);
    	// 6. 모든 사원정보 다시 가져와 보여주기
    	this.showAllEmpInfo();
    }//-----------------------------

    private void btFindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btFindActionPerformed
        String fname = JOptionPane.showInputDialog("검색할 사원의 이름을 입력하세요");
        if(fname==null) return;
        ArrayList<EmpVO> arr = empDao.findEmp(fname);
        if(arr!=null && arr.size()>0)
        	this.showEmpTable(arr);
        else showMsg("검색 정보가 없습니다.");
    }//-----------------------------

    private void btEdelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEdelActionPerformed
        // 1. 삭제할 회원번호를 tempno로부터 얻어오기
    	String empno = tempno.getText();
    	if(empno==null||empno.trim().isEmpty()) {
        	showMsg("삭제할 사원을 테이블에서 선택하세요.");
        	return;
        }
    	// 2. Confirm 대화상자를 띄워 정말 삭제하겠냐고 확인
        int yn = JOptionPane.showConfirmDialog(this, empno+"번 사원을 정말 삭제하시겠어요?",
        		"삭제 확인", JOptionPane.YES_NO_OPTION);
        if (yn==JOptionPane.NO_OPTION) return;
        // 3. 삭제하겠다고 하면 empDao의 deleteEmp() 호출
        boolean result = empDao.deleteEmp(empno);
        // 4. 그 결과 메시지 처리
        String message = (result)? "삭제 성공": "삭제 실패";
        showMsg(message);
        // 5. 모든 사원 정보 가져오기
        this.showAllEmpInfo();
    }//-----------------------------

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
            	System.out.println(info.toString());
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmpManagerGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmpManagerGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmpManagerGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmpManagerGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EmpManagerGui().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btDadd;
    private javax.swing.JButton btDdel;
    private javax.swing.JButton btDlist;
    private javax.swing.JButton btEadd;
    private javax.swing.JButton btEdel;
    private javax.swing.JButton btEedit;
    private javax.swing.JButton btFind;
    private javax.swing.JButton btElist;
    		javax.swing.JComboBox cdname;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane tabPane;
    		javax.swing.JTable tableDept;
    		javax.swing.JTable tableEmp;
    		javax.swing.JTextField tcomm;
    		javax.swing.JTextField tdeptno;
    		javax.swing.JTextField tdname;
    		javax.swing.JTextField tempno;
    		javax.swing.JTextField tename;
    		javax.swing.JTextField thiredate;
    		javax.swing.JTextField tjob;
    		javax.swing.JTextField tloc;
    		javax.swing.JTextField tsal;
    // End of variables declaration//GEN-END:variables
}
